source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.0"
gem "pg", "~> 1.4"
gem "puma", "~> 6.0"
gem "bcrypt", "~> 3.1.18"
gem "jwt", "~> 2.6"
gem "rack-cors", "~> 1.1"
gem "bootsnap", ">= 1.4.4", require: false
# Add any other production gems (e.g., sentry-raven) as needed